before:
  hooks:
    - go mod download

builds:
  - id: echo
    main: cmd/echo/main.go
    binary: executor_echo_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
      - darwin
    goarch: &goarch
      - amd64
      - arm64
    goarm: &goarm
      - 7

  - id: msg
    main: cmd/msg/main.go
    binary: executor_msg_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

  - id: ticker
    main: cmd/ticker/main.go
    binary: source_ticker_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

  - id: forwarder
    main: cmd/forwarder/main.go
    binary: source_forwarder_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

snapshot:
  name_template: 'v{{ .Version }}'


release:
  # If set to true, will not auto-publish the release.
  draft: false
  prerelease: auto

  # Add extra pre-existing files to the release.
  # - build plugin index.yaml
  extra_files:
    - glob: ./plugins-index.yaml
